### ISSUE TITLE
missing spring.thymeleaf.cache=false

### ISSUE THREAD

**Issue by Cyrille37** [spring-guides/gs-serving-web-content#10]
Hi,
I've just try gs-serving-web-content-complete in SpringIDE and was disappointed when modifying the "greeting.html" template and do not see change in the browser (template was not reloaded).

After searching into the web I found that adding the file ```scr/main/resources/application.properties```
with the line ```spring.thymeleaf.cache=false``` resolve the case.

I think you could add this tip to make people happy to discover that Java web app can reload changes without restarting web server (an old bad story).

Cheers.

**Comment by gregturn** [comment]
That's a good point, although my temptation is to actually add spring-boot-devtools. It has the effect of flipping that flag as desired, but also switching some other features people may wish to use. And I think it would better align with the message we want to share with devs.

**Comment by Cyrille37** [comment]
I can meet many devs that hate Web Java techs for those little missing tips ...

**Comment by Cyrille37** [comment]
perhaps completing the page "http://blog.netgloo.com/2014/05/21/hot-swapping-in-spring-boot-with-eclipse-sts/" with your experience on "spring-boot-devtools" should be a way to an easy Web Java life ;-)

**Comment by Cyrille37** [comment]
Your solution is explained in the Spring documentation on chapter 78 (after a long way...)
http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-hotswapping
