### ISSUE TITLE
Linkfix for thymeleaf link

### ISSUE THREAD

**Issue by pieterhumphrey** [spring-guides/gs-serving-web-content#12]
On this page
https://spring.io/guides/gs/serving-web-content/

If you search thymeleaf on that page, the first link is broken. I
think the correct link should be
http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html, but
not 100% sure.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-serving-web-content/commit/99a8bb77758a2d041bfadaaf6c8241fd59d27ae7
