### ISSUE TITLE
unable to call web application from the spring boot to send params through url

### ISSUE THREAD

**Issue by balu123456** [spring-guides/gs-serving-web-content#13]
I am try to using Angularjs2 with spring boot application every thing working fine with the small issue.

Description:

step1. if we have default router like router('') meaning localhost:8080/ it is calling index.html page with out having issues.

step2. if we have added context path like router('accountsummary') meaning localhost:8080/accountsummary its not working. when i give like below configuration in spring boot conf like below:

@Configuration
public class WebController extends WebMvcConfigurerAdapter{
 public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/accountSummary").setViewName("index.html");
    }
}

it was working fine.

3. when i want to configure like route('accountsummary/:reqid). reqid is the parameter meaning i want to call like localhost:8080/accountsummary/abc it is not working. i have given like (/**)

@Configuration
public class WebController extends WebMvcConfigurerAdapter{
 public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/accountSummary/**").setViewName("index.html");
    }
}

its not working and giving like below:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jun 30 15:11:38 EDT 2016
There was an unexpected error (type=Not Found, status=404).
No message available

Can any one please help me out

**Comment by gregturn** [comment]
Please don't open multiple tickets for the same issue.
