### ISSUE TITLE
https://spring.io/guides/gs/serving-web-content/ Broken

### ISSUE THREAD

**Issue by 7--** [spring-guides/gs-serving-web-content#18]
You can't run this on a separate Tomcat server because your parent pom is providing the jar. Also it's broken because this only works on a specific version of Tomcat in the pom properties.         <tomcat.version>7.0.75</tomcat.version>

But the bigger problem is it not working on server. What's the point of a web tutorial if you can't run it on a server? They would literally have to rewrite nearly the entire pom and hunt down a ton of dependencies just to get it running. Rewrite this tutorial so it will actually work in typical situations.

**Comment by gregturn** [comment]
If your question is "how do I build a WAR instead of a runnable JAR", we have a guide with suitable links to help here => https://spring.io/guides/gs/convert-jar-to-war/

If that is not what you're asking please clarify what you mean by "typical situations".

**Comment by 7--** [comment]
I just tried that it didnt work. It's not giving any errors just 404s. My classes are the same as the tutorial

Sep 28, 2017 8:06:43 PM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNING: [SetPropertiesRule]{Server/Service/Engine/Realm/Realm} Setting property 'receName' to 'UserDatabase' did not find a matching property.
Sep 28, 2017 8:06:43 PM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:rest-service' did not find a matching property.
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version:        Apache Tomcat/7.0.75
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Jan 18 2017 20:54:42 UTC
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:         7.0.75.0
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Windows 7
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            6.1
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             C:\Program Files\Java\jdk1.8.0_25\jre
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_25-b18
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         C:\Users\vn60789\Documents\EclipseWorkspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp3
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         C:\apache-tomcat-7.0.75
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=C:\Users\vn60789\Documents\EclipseWorkspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp3
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=C:\apache-tomcat-7.0.75
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dwtp.deploy=C:\Users\vn60789\Documents\EclipseWorkspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp3\wtpwebapps
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=C:\apache-tomcat-7.0.75\endorsed
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=Cp1252
Sep 28, 2017 8:06:43 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: C:\Program Files\Java\jdk1.8.0_25\jre\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:/Program Files (x86)/Eclipse 4.4/jre/bin/client;C:/Program Files (x86)/Eclipse 4.4/jre/bin;C:/Program Files (x86)/Eclipse 4.4/jre/lib/i386;C:\Windows\System32;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExtensions\;C:\Program Files (x86)\Reflection\;C:\Program Files\Common Files\ThinPrint\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\WinPython27\python-2.7.6;C:\Program Files\Java\jdk1.8.0_25\bin;C:\Toolbox\apache-maven-3.3.3\bin;\\dwshome-c.homeoffice.wal-mart.com\dwsuserdata$\vn60789\Desktop;;.
Sep 28, 2017 8:06:43 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Sep 28, 2017 8:06:43 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Sep 28, 2017 8:06:43 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1040 ms
Sep 28, 2017 8:06:43 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Sep 28, 2017 8:06:43 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.75
Sep 28, 2017 8:06:44 PM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [147] milliseconds.
Sep 28, 2017 8:06:45 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Sep 28, 2017 8:06:46 PM org.apache.catalina.core.ApplicationContext log
INFO: 1 Spring WebApplicationInitializers detected on classpath
Sep 28, 2017 8:06:46 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Sep 28, 2017 8:06:46 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Sep 28, 2017 8:06:46 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 2244 ms


This is my pom now
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.springframework</groupId>
    <artifactId>gs-serving-web-content</artifactId>
    <version>0.1.0</version>
	<packaging>war</packaging>
	
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.7.RELEASE</version>
    </parent>

    <dependencies>
 
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <properties>
        <java.version>1.8</java.version>
        <tomcat.version>7.0.75</tomcat.version>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>1.5.7.RELEASE</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>`

**Comment by gregturn** [comment]
I think the problem is your pinning it to Tomcat 7. Boot 1.5 uses Tomcat 8.5 which has servlet 3.1 whereas 7 I believe only has servlet 3.0. In essence this is an unsupported configuration.

**Comment by 7--** [comment]
I don't have tomcat 8. I'm using tomcat 7.75 servlet 3.0. Do you know which Boot version would work with tomcat7.75

**Comment by gregturn** [comment]
You'd have to go back to 1.1. 1.2 moved to Tomcat 8.0.

**Comment by 7--** [comment]
Same problem still :(

It seems like tomcat picked it up:

**Comment by gregturn** [comment]
Actually just go back to when the guide supported 1.1. 

https://github.com/spring-guides/gs-serving-web-content/tree/fdf7a8a50840f063cbd1f38eaf3b9a8dfcf35142

You can find the matching version of the WAR guide and see if that helps.

**Comment by gregturn** [comment]
The ref docs on Boot 1.1 for WAR files => https://docs.spring.io/spring-boot/docs/1.1.9.RELEASE/reference/htmlsingle/#build-tool-plugins-maven-packaging

**Comment by 7--** [comment]
Thanks a bunch I'll look at this tomorrow

**Comment by 7--** [comment]
I still can't get it working. Tomcat seems to pick it up but I'm not getting any errors just 404s. I place gs-serving-web-content-0.1.0.war in apache-tomcat-7.0.75\webapps\ and start tomcat. Using URL http://localhost:8080/gs-serving-web-content-0.1.0
I was able to run my other war project this way. I was expecting to at least see the static/index.html page. but also tried URLs http://localhost:8080/gs-serving-web-content-0.1.0/greeting and http://localhost:8080/greeting

INFO: Deployment of web application archive C:\apache-tomcat-7.0.75\webapps\gs-s
erving-web-content-0.1.0.war has finished in 1,656 ms

`
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version:        Apache Tomcat/7.0.75
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Jan 18 2017 20:54:42 UTC
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:         7.0.75.0
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Windows 7
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            6.1
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             C:\Program Files\Java\jdk1.8.0_25\jre
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_25-b18
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         C:\apache-tomcat-7.0.75
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         C:\apache-tomcat-7.0.75
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.config.file=C:\apache-tomcat-7.
0.75\conf\logging.properties
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLo
aderLogManager
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=C:\apache-tomcat-7.0.75\endors
ed
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=C:\apache-tomcat-7.0.75
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=C:\apache-tomcat-7.0.75
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=C:\apache-tomcat-7.0.75\temp
Sep 29, 2017 6:00:15 PM org.apache.catalina.core.AprLifecycleListener lifecycleE
vent
INFO: The APR based Apache Tomcat Native library which allows optimal performanc
e in production environments was not found on the java.library.path: C:\Program
Files\Java\jdk1.8.0_25\jre\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Wi
ndows;C:\Windows\System32;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExt
ensions\;C:\Program Files (x86)\Reflection\;C:\Program Files\Common Files\ThinPr
int\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86
)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server
\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Prog
ram Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\WebEx\
Productivity Tools;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Wi
nPython27\python-2.7.6;C:\Program Files\Java\jdk1.8.0_25\bin;C:\Toolbox\apache-m
aven-3.3.3\bin;.
Sep 29, 2017 6:00:15 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Sep 29, 2017 6:00:15 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 595 ms
Sep 29, 2017 6:00:15 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Sep 29, 2017 6:00:15 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.75
Sep 29, 2017 6:00:15 PM org.apache.catalina.startup.HostConfig deployWAR
**INFO: Deploying web application archive C:\apache-tomcat-7.0.75\webapps\gs-servi
ng-web-content-0.1.0.war**
Sep 29, 2017 6:00:16 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug
logging for this logger for a complete list of JARs that were scanned but no TLD
s were found in them. Skipping unneeded JARs during scanning can improve startup
 time and JSP compilation time.
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive C:\apache-tomcat-7.0.75\webapps\gs-s
erving-web-content-0.1.0.war has finished in 1,656 ms
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\apache-tomcat-7.0.75\webapps\docs
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory C:\apache-tomcat-7.0.75\webapps\do
cs has finished in 47 ms
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\apache-tomcat-7.0.75\webapps\exampl
es
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory C:\apache-tomcat-7.0.75\webapps\ex
amples has finished in 328 ms
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\apache-tomcat-7.0.75\webapps\host-m
anager
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory C:\apache-tomcat-7.0.75\webapps\ho
st-manager has finished in 47 ms
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\apache-tomcat-7.0.75\webapps\manage
r
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory C:\apache-tomcat-7.0.75\webapps\ma
nager has finished in 47 ms
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory C:\apache-tomcat-7.0.75\webapps\ROOT
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory C:\apache-tomcat-7.0.75\webapps\RO
OT has finished in 47 ms
Sep 29, 2017 6:00:17 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Sep 29, 2017 6:00:17 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Sep 29, 2017 6:00:17 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 2312 ms
`

`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.springframework</groupId>
    <artifactId>gs-serving-web-content</artifactId>
    <version>0.1.0</version>
	<packaging>jar</packaging>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>0.5.0.M6</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring3</artifactId>
        </dependency>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency> 
    </dependencies>

    <properties>
        <start-class>hello.Application</start-class>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
				<version>1.1.9.RELEASE</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-milestone</id>
            <url>http://repo.spring.io/libs-milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>spring-milestone</id>
            <url>http://repo.spring.io/libs-milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

</project>
`
`
package hello;

import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.SpringApplication;
import org.springframework.context.annotation.ComponentScan;

@ComponentScan
@EnableAutoConfiguration
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
`
`
package hello;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class GreetingController {

    @RequestMapping("/greeting")
    public String greeting(@RequestParam(value="name", required=false, defaultValue="World") String name, Model model) {
        model.addAttribute("name", name);
        return "greeting";
    }

}
`

**Comment by dsyer** [comment]
Please can you learn how to format your code snippets and logs (I edited that last one for you). Also, please don't paste and entire project into an issue comment - just link to the code in github. If you did that we'd have a better chance of helping. Did you forget to add a `SpringBootServletInitializer` (per the instructions in the guide that Greg posted)?

**Comment by 7--** [comment]
https://github.com/7--/SpringBoot1.5.7

When I extend SpringBootServletInitializer I get SEVERE: A child container failed during start

**Comment by dsyer** [comment]
I sent a PR to  your project (https://github.com/7--/SpringBoot1.5.7/pull/1). It works for me with Spring Boot 1.3.8.

**Comment by 7--** [comment]
Thank you works like charm. I'm surprised servlet 3.1 works. Can't thank you enough.
