### ISSUE TITLE
javax.servlet.ServletException: Circular view path [greeting]: would dispatch back to the current handler URL [/greeting] again. 

### ISSUE THREAD

**Issue by zeleven** [spring-guides/gs-serving-web-content#19]
The example project can't work, I got the error `javax.servlet.ServletException: Circular view path [greeting]: would dispatch back to the current handler URL [/greeting] again. ` when I access the `/greeting`

**Comment by zeleven** [comment]
Sorry, it's my mistake.

**Comment by ar7n** [comment]
@zeleven i have same problem. What does it was?)

**Comment by ar7n** [comment]
@JavaHelper i downgraded version of spring or thymeleaf. I can't remember exactly which one it was.

**Comment by reach009** [comment]
I solved this problem by adding the spring-boot-starter-thymeleaf
Here is the code:
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>

**Comment by johnmilimo** [comment]
I experienced a similar problem today. All the suggestions I got online could not help, until I tried the below:

I had annotated my controller using `@Controller`  > `import org.springframework.stereotype.Controller`

I replaced the above with `@RestController` > `import org.springframework.web.bind.annotation.RestController`

And it got working.

**Comment by abhidutz** [comment]
I fixed mine by using spring boot <version>2.2.2.RELEASE</version>

**Comment by mohiniyadav** [comment]
Converting @Contoller to @RestController resolved this issue.

**Comment by hzwplus** [comment]
Thanks @johnmilimo, replacing `@Controller` with `@RestController` works for me. It save my ton of time. But why?

**Comment by gyokutoku** [comment]
> Thanks @johnmilimo, replacing `@Controller` with `@RestController` works for me. It save my ton of time. But why?

I don't think it resolved your problem. After chaning it to "RestController", it just return the "greeting" string itself -- that's not a view page.
I just found it won't work after using Java11/Java17 (Springoboot is now 2.6.3).
