### ISSUE TITLE
Make it clearer that the guide uses Thymeleaf

### ISSUE THREAD

**Issue by wilkinsona** [spring-guides/gs-serving-web-content#24]
With reference to https://github.com/spring-projects/spring-boot/pull/13536, it would be good if this guide made it clearer that it uses Thymeleaf. Perhaps that could be as simple as updating the repository's description:

```
Serving Web Content with Spring MVC :: Learn how to create a web page with Spring MVC and Thymeleaf.
```

**Comment by dsyer** [comment]
Duplicates #26. The description already has "Thymeleaf" in it. Maybe someone esle fixed it (or maybe I didn't understand the suggestion).
