### ISSUE TITLE
Circular view path [greeting]: would dispatch back to the current handler URL [/greeting] again.

### ISSUE THREAD

**Issue by pmihalcin** [spring-guides/gs-serving-web-content#26]
When I go to http://localhost:8080/greeting, I am getting `Circular view path [greeting]: would dispatch back to the current handler URL [/greeting] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)`

**Comment by hannesgeodan** [comment]
yes, here too!

**Comment by hannesgeodan** [comment]
@gregturn have you seen this error?

**Comment by Vovchikus** [comment]
Use exact dependencies from pom.xml

**Comment by reach009** [comment]
same issue here...if anyone knows the solution, please share!

**Comment by reach009** [comment]
Hey guys, I just found a good solution. 

Just add thymeleaf dependency:

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>

**Comment by divyashree249** [comment]
i added the thymeleaf dependency so i got error in dependency .

**Comment by 17343149** [comment]
I solved this problem by add thymeleaf dependency in build.gradle
dependencies {
	compile "org.springframework.boot:spring-boot-starter-thymeleaf"
}
