### ISSUE TITLE
Broken link https://spring.io/understanding/view-templates

### ISSUE THREAD

**Issue by deisner** [spring-guides/gs-serving-web-content#35]
This guide links 'view technology' (in "The implementation of the method body relies on a view technology ...") to https://spring.io/understanding/view-templates, but that page is currently a 404.

**Comment by Buzzardo** [comment]
All of the understanding content got removed quite some time ago (before I started). I have been removing these links as I find them. I'll fix this one.

**Comment by deisner** [comment]
Thanks. Any sense of when it will go live?

**Comment by dsyer** [comment]
Already live as far as I know.

**Comment by deisner** [comment]
No, the broken link is still there. Visit https://spring.io/guides/gs/serving-web-content/ and then click on the "view technology" hyperlink:

![image](https://user-images.githubusercontent.com/742277/70542554-e86f1780-1b36-11ea-8772-55ece1080109.png)

You'll get a 404.

**Comment by dsyer** [comment]
Right. Got it. Fixed in #34.
