### ISSUE TITLE
The document title should be changed as Serving Web Content with Spring Boot

### ISSUE THREAD

**Issue by am-firnas** [spring-guides/gs-serving-web-content#39]
Hi,

I actually faced confusion when the title implies as **Spring MVC** instead **Spring Boot** in there.
https://stackoverflow.com/a/61704317/5781900

**Comment by dsyer** [comment]
Spring Boot is using Spring MVC (as opposed to some other web framework) in the sample app here. I think the title is fine, but maybe we could be more clear about the distinction.

**Comment by am-firnas** [comment]
yes, true. But when it comes to running configurations or **run the solution using an** **IDE** I think that's where causes confusion, whether to create new servers or go with the embedded server which spring boot attaches on run time. since the user guide aim for begineers I just had a kind of a thought. :)

**Comment by dsyer** [comment]
Does it mention anything about creating a new server in the IDE? I’m happy to make things clearer but I’m not quite sure precisely what the problem is yet.

**Comment by am-firnas** [comment]
no, the documentation is perfect, since it is basically prefer to use Text editors to get more familiar for beginners like me. I actually tried wit IDE's with the Tomcat server attached to configurations already. So that made me little hard to get it done when I faced 'port already use errors'. 

Yes, anyways I realize now this issue is subjective and can be closed.
