### ISSUE TITLE
dependency versions

### ISSUE THREAD

**Issue by jtal** [spring-guides/gs-serving-web-content#5]
Hello,

I am trying to go through the tutorial linked below. I am using STS and started by creating a new maven project with no archetype specified.

I was directed to this github project for pom.xml. However, eclipse is complaining that there is not version element within the dependencies.

I must me missing something?

http://spring.io/guides/gs/serving-web-content/#scratch

**Comment by dimmel82** [comment]
Ignore the "Update for work item spring-guides#5" from my fork, the reference was by mistake
